/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CalculadoraBlockchain__factory } from "./CalculadoraBlockchain__factory";
export { Lock__factory } from "./Lock__factory";
