/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CalculadoraBlockchainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dividir"
      | "multiplicar"
      | "obtenerUltimoResultado"
      | "restar"
      | "sumar"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OperacionRealizada"): EventFragment;

  encodeFunctionData(
    functionFragment: "dividir",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplicar",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerUltimoResultado",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restar",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sumar",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "dividir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiplicar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerUltimoResultado",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "restar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sumar", data: BytesLike): Result;
}

export namespace OperacionRealizadaEvent {
  export type InputTuple = [
    tipo: string,
    a: BigNumberish,
    b: BigNumberish,
    resultado: BigNumberish
  ];
  export type OutputTuple = [
    tipo: string,
    a: bigint,
    b: bigint,
    resultado: bigint
  ];
  export interface OutputObject {
    tipo: string;
    a: bigint;
    b: bigint;
    resultado: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CalculadoraBlockchain extends BaseContract {
  connect(runner?: ContractRunner | null): CalculadoraBlockchain;
  waitForDeployment(): Promise<this>;

  interface: CalculadoraBlockchainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dividir: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  multiplicar: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  obtenerUltimoResultado: TypedContractMethod<[], [bigint], "view">;

  restar: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  sumar: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dividir"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multiplicar"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "obtenerUltimoResultado"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "restar"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sumar"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "OperacionRealizada"
  ): TypedContractEvent<
    OperacionRealizadaEvent.InputTuple,
    OperacionRealizadaEvent.OutputTuple,
    OperacionRealizadaEvent.OutputObject
  >;

  filters: {
    "OperacionRealizada(string,int256,int256,int256)": TypedContractEvent<
      OperacionRealizadaEvent.InputTuple,
      OperacionRealizadaEvent.OutputTuple,
      OperacionRealizadaEvent.OutputObject
    >;
    OperacionRealizada: TypedContractEvent<
      OperacionRealizadaEvent.InputTuple,
      OperacionRealizadaEvent.OutputTuple,
      OperacionRealizadaEvent.OutputObject
    >;
  };
}
