/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CalculadoraBlockchain } from "./CalculadoraBlockchain";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { CalculadoraBlockchain__factory } from "./factories/CalculadoraBlockchain__factory";
export { Lock__factory } from "./factories/Lock__factory";
